USE Biltiful;

SET LANGUAGE 'Brazilian'

CREATE TABLE Cliente (
	CPF             NVARCHAR(14) NOT NULL,
	Nome            NVARCHAR(50) NOT NULL,
	DataNasc        DATE NOT NULL,
	Sexo            CHAR(1) NOT NULL,
	UltimaCompra    DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	DataCadastro    DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Situacao        CHAR(1) NOT NULL DEFAULT 'A',
	Risco			BIT NOT NULL DEFAULT 0

	CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY (CPF),
	CONSTRAINT UN_CPF_NOME_CLIENTE UNIQUE (CPF, Nome)
);

CREATE TABLE Fornecedor (
	CNPJ            NVARCHAR(18) NOT NULL,
	Razao_Social    NVARCHAR(50) NOT NULL,
	Data_Abertura   DATE NOT NULL, 
	Ultima_Compra   DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Data_Cadastro   DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Situacao        CHAR(1) NOT NULL DEFAULT 'A',
	Bloqueado		BIT NOT NULL DEFAULT 0

	CONSTRAINT PK_CNPJ_FORNECEDOR PRIMARY KEY (CNPJ),
	CONSTRAINT UN_CNPJ_RAZAO_SOCIAL_FORNECEDOR UNIQUE (CNPJ, Razao_Social)
);

CREATE TABLE Materia_Prima (
	ID              INT IDENTITY NOT NULL,
	Nome            NVARCHAR(20) NOT NULL,
	Ultima_Compra   DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Data_Cadastro   DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Situacao        CHAR(1) NOT NULL DEFAULT 'A'

	CONSTRAINT PK_ID_MATERIA_PRIMA PRIMARY KEY(ID),
	CONSTRAINT UN_ID_NOME_MATERIA_PRIMA UNIQUE (ID, Nome)
);

CREATE TABLE Produto (
	Codigo_Barras	 NVARCHAR(13) NOT NULL,
	Nome	         NVARCHAR(20) NOT NULL,
	Valor_Venda	     DECIMAL (5,2) NOT NULL,
	Ultima_Venda     DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Data_Cadastro	 DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
	Situacao		 CHAR(1) NOT NULL DEFAULT 'A'

	CONSTRAINT PK_CODIGO_BARRAS_PRODUTO PRIMARY KEY(Codigo_Barras),
	CONSTRAINT UN_CODIGO_BARRAS_NOME_PRODUTO UNIQUE (Codigo_Barras, Nome)
);

CREATE TABLE Venda (
    ID			     INT NOT NULL,
    Data_Venda       DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
    CPF_Cliente      NVARCHAR(14) NOT NULL,
    Valor_Total      DECIMAL(7,2) NOT NULL DEFAULT 0,
    
    CONSTRAINT PK_ID_VENDA PRIMARY KEY (ID),
	CONSTRAINT FK_CPF_CLIENTE_VENDA FOREIGN KEY (CPF_Cliente) REFERENCES Cliente(CPF)
);

CREATE TABLE Item_Venda (
    ID				INT NOT NULL,
    Produto			NVARCHAR(13) NOT NULL,
    Quantidade      INT NOT NULL,
    Valor_Unitario  DECIMAL(5,2) NOT NULL,
    Total_Item      DECIMAL(6,2) NOT NULL,

	CONSTRAINT FK_ID_ITEM_VENDA FOREIGN KEY (ID) REFERENCES Venda(ID),
	CONSTRAINT FK_PRODUTO_ITEM_VENDA FOREIGN KEY (Produto) REFERENCES Produto(Codigo_Barras)	
);

CREATE TABLE Compra (
    ID              INT NOT NULL,
    Data_Compra     DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
    Fornecedor      NVARCHAR(18) NOT NULL,
    Valor_Total     DECIMAL(7,2) NOT NULL DEFAULT 0,
    
    CONSTRAINT PK_ID_COMPRA PRIMARY KEY(ID),
    CONSTRAINT FK_FORNECEDOR_COMPRA FOREIGN KEY (Fornecedor) REFERENCES Fornecedor(CNPJ)
);

CREATE TABLE Item_Compra
(
    ID               INT NOT NULL,
    Data_Compra      DATE NOT NULL,
    Materia_Prima    INT NOT NULL,
    Quantidade       DECIMAL(5,2) NOT NULL,
    Valor_Unitario   DECIMAL(5,2) NOT NULL,
    Total_Item       DECIMAL(6,2) NOT NULL,

	CONSTRAINT FK_ID_ITEM_COMPRA FOREIGN KEY (ID) REFERENCES Compra(ID),
	CONSTRAINT FK_MATERIA_PRIMA_ITEM_COMPRA FOREIGN KEY (Materia_Prima) REFERENCES Materia_Prima(ID)
);

CREATE TABLE Producao (
    ID              INT NOT NULL,
    DataProducao    DATE NOT NULL DEFAULT CONVERT(DATE, GETDATE()),
    Produto         NVARCHAR(13) NOT NULL,
    Quantidade      DECIMAL(5,2) NOT NULL,
    
    CONSTRAINT PK_ID_PRODUCAO PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUTO_PRODUCAO FOREIGN KEY (Produto) REFERENCES Produto(Codigo_Barras)    
);

CREATE TABLE Item_Producao
(
    ID							INT NOT NULL,
    Data_Producao				DATE NULL,
    Materia_Prima				INT NOT NULL,
    Quantidade_Materia_Prima    DECIMAL (5,2) NOT NULL,

	CONSTRAINT FK_ID_ITEM_PRODUCAO FOREIGN KEY (ID) REFERENCES Producao(ID),
	CONSTRAINT FK_MATERIA_PRIMA_ITEM_PRODUCAO FOREIGN KEY (Materia_Prima) REFERENCES  Materia_Prima(ID) 
);